"""Add SpindleFinance tables

Revision ID: a10086e19b3c
Revises: ab328ab7aa51
Create Date: 2026-02-19 19:14:04.891106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10086e19b3c'
down_revision = 'ab328ab7aa51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_info', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Invoice',
    sa.Column('inv_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('amt_recievable', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('inv_id')
    )
    # AccountCashflow table already exists in the initial migration.  
    # Instead of recreating it, we'll add just the foreign key constraint to
    # the newly-added Invoice table.  Any column additions (invoice_id) are
    # handled in a subsequent revision (756c34bf27be).
    # (Alembic autogenerate mistakenly generated a full create here when the
    # table was modified after the initial migration.)
    #
    # Note: the upgrade path ensures Invoice is present before we create the
    # foreign key.
    op.create_foreign_key(
        'fk_accountcashflow_invoice',
        'AccountCashflow',
        'Invoice',
        ['invoice_id'],
        ['inv_id'],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AccountCashflow')
    op.drop_table('Invoice')
    op.drop_table('clients')
    # ### end Alembic commands ###
