"""Add SpindleFinance tables

Revision ID: a10086e19b3c
Revises: ab328ab7aa51
Create Date: 2026-02-19 19:14:04.891106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10086e19b3c'
down_revision = 'ab328ab7aa51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_info', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Invoice',
    sa.Column('inv_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('amt_recievable', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('inv_id')
    )
    op.create_table('AccountCashflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=True),
    sa.Column('txn_name', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=250), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('txn_type', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reference_id', sa.String(length=25), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['Invoice.inv_id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AccountCashflow')
    op.drop_table('Invoice')
    op.drop_table('clients')
    # ### end Alembic commands ###
