"""Add SpindleStock tables

Revision ID: ab328ab7aa51
Revises: 05e05066b459
Create Date: 2026-02-10 16:56:56.492000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab328ab7aa51'
down_revision = '05e05066b459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_produced', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('inward_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.Column('raw_material_id', sa.Integer(), nullable=True),
    sa.Column('quantity_used', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['production_id'], ['production.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_material')
    op.drop_table('raw_material')
    op.drop_table('production')
    op.drop_table('finished_stock')
    # ### end Alembic commands ###
